package org.apache.jsp.jlb;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.saturn.website.PaginationUtils;
import com.saturn.website.Article;
import java.util.List;
import com.saturn.website.WebUtils;
import com.saturn.website.Content;
import java.util.List;
import com.saturn.website.Article;
import com.saturn.website.WebUtils;
import com.saturn.website.Content;
import com.saturn.website.CountPerson;
import java.util.List;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(6);
    _jspx_dependants.add("/jlb/../include/include.jsp");
    _jspx_dependants.add("/jlb/include/top.jsp");
    _jspx_dependants.add("/jlb/include/left.jsp");
    _jspx_dependants.add("/jlb/include/roll.jsp");
    _jspx_dependants.add("/jlb/include/foot.jsp");
    _jspx_dependants.add("/jlb/include/cs.jsp");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=EmulateIE7\" />\n");
      out.write("<title>金兰宝科技有限公司</title>\n");
      out.write("\n");
      out.write("\n");
      out.write("<link rel=\"shortcut icon\" href=\"../favicon.ico\" type=\"image/x-icon\" />\n");
      out.write("<meta name=\"description\" content=\"金兰宝\" />\n");
      out.write("<meta name =\"keywords\" content=\"金兰宝\">\n");
      out.write("\n");
      out.write(" <script src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/js/jquery-1.9.1.min.js\" type=\"text/javascript\"></script>\n");
      out.write(" <script src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/js/jquery.litenav.js\" type=\"text/javascript\"></script>\n");
      out.write(" <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/js/lrtk.js\"></script>\n");
      out.write(" <link href=\"");
      out.print(request.getContextPath());
      out.write("/jlb/css/index.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write(" \n");
      out.write(" <link href=\"");
      out.print(request.getContextPath());
      out.write("/jlb/css/style.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write(" <link href=\"");
      out.print(request.getContextPath());
      out.write("/jlb/css/top.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write(" <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/js/pageMenuBar.js\"></script>\n");
      out.write(" <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/js/imgscroll.js\"></script>\n");
      out.write(" <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/js/back-to-top.js\"></script>\n");
      out.write(" <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/js/Marquee.js\"></script> \n");
      out.write("\n");
      out.write(" <script type=\"text/javascript\">\n");
      out.write("var type='");
      out.print(request.getParameter("type"));
      out.write("'\n");
      out.write("var cid = '");
      out.print(request.getParameter("cid"));
      out.write("';\n");
      out.write("var did = '");
      out.print(request.getParameter("did"));
      out.write("';\n");
      out.write("var opt={aid:cid,start:'0',offset:'25'};\n");
      out.write("$(function() {\n");
      out.write("\tgetArticleListByPage(cid,1,0);\n");
      out.write("\tgetMenuTitle(cid);\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("function getMenuTitle(cid){\n");
      out.write("\t//获得菜单标题\n");
      out.write("\t$.post(\"");
      out.print(request.getContextPath());
      out.write("/webdo/menu/menubycid.do\", \n");
      out.write("\t\t\t{cid:cid}, \n");
      out.write("\t\t\tfunction(json){\n");
      out.write("\t\t\t\t$(\"#topmenu\").html(json.name);\n");
      out.write("\t\t\t\t$(\"#topmenu_z\").html(json.name);\n");
      out.write("\t\t\t}, \n");
      out.write("\t\t\t\"json\");\n");
      out.write("}\n");
      out.write("\n");
      out.write("function getArticleListByPage(aid,pageNo,start){\n");
      out.write("\topt.start=start;\n");
      out.write("\t//获得文章列表\n");
      out.write("\tif(type!=null&&type!=\"\"&&type==\"search\"){\n");
      out.write("\t\topt.aid=aid;\n");
      out.write("\t\t$.post(\"");
      out.print(request.getContextPath());
      out.write("/webdo/recommend/searchArticle.do\", \n");
      out.write("\t\t\t\topt,\n");
      out.write("\t\t\t\tfunction(json){\n");
      out.write("\t\t\t\t\tvar str = \"\";\n");
      out.write("\t\t\t\t\t$(\"#artlist\").html(str);\n");
      out.write("\t\t\t\t\tvar num = json.rows.length;\n");
      out.write("\t\t\t\t\tvar aid = \"\";\n");
      out.write("\t\t\t\t\tif(num>0){\n");
      out.write("\t\t\t\t\t\tfor(var i=0;i<num;i++) {\n");
      out.write("\t\t\t\t\t\t\tvar id = json.rows[i].id;\n");
      out.write("\t\t\t\t\t\t\tvar image = json.rows[i].image;\n");
      out.write("\t\t\t\t\t\t\tvar title = json.rows[i].title;\n");
      out.write("\t\t\t\t\t\t\tvar datetime = json.rows[i].createTime.substr(0,10);\n");
      out.write("\t\t\t\t\t\t\tvar url=\"");
      out.print(request.getContextPath());
      out.write("/jlb/detail.jsp?cid=\"+cid+\"&did=\"+id;\n");
      out.write("\t\t\t\t\t\t\t//aid 赋值\n");
      out.write("\t\t\t\t\t\t\tif (did == null||did==\"\"||did==\"null\") {\n");
      out.write("\t\t\t\t\t\t\t\t//aid = \"ccgdzs.new01.n1\";\n");
      out.write("\t\t\t\t\t\t\t\tdid = id;\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\tstr=$(\"#artlist\").html()+\"<li><a href=\\\"\"+url+\"\\\">\"+title+\"</a><span style=\\\"float:right;margin-right:20px;\\\">\"+datetime+\"</span></li>\";\n");
      out.write("\t                    \n");
      out.write("\t\t\t\t\t\t\t$(\"#artlist\").html(str);\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t}else{\n");
      out.write("\t\t\t\t\t\t$(\"#artlist\").html(\"没有文章\");\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\tvar totle = json.total;\n");
      out.write("\t\t\t\t\t//分页\n");
      out.write("\t\t\t\t\t$(\"#pagemenu\").pageMenuBar({\n");
      out.write("\t\t\t\t\t\trowPerPage:parseInt(opt.offset),\n");
      out.write("\t\t\t\t\t\tsumRow:parseInt(totle), \n");
      out.write("\t\t\t\t\t\tpageNo:parseInt(pageNo),\n");
      out.write("\t\t\t\t\t\tstate:1,\n");
      out.write("\t\t\t\t\t\tfunc:'getArticleListByPage',\n");
      out.write("\t\t\t\t\t\targs:'\"'+cid+'\"'\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\t\t\t\t}, \n");
      out.write("\t\t\t\t\"json\");\n");
      out.write("\t}else if(type!=null&&type!=\"\"&&type==\"cgal\"){\n");
      out.write("\t\t$.post(\"");
      out.print(request.getContextPath());
      out.write("/webdo/article/articleListByPage.do\", \n");
      out.write("\t\t\t\topt,\n");
      out.write("\t\t\t\tfunction(json){\n");
      out.write("\t\t\t\t\tvar str = \"\";\n");
      out.write("\t\t\t\t\t$(\"#artlist\").html(str);\n");
      out.write("\t\t\t\t\tvar num = json.rows.length;\n");
      out.write("\t\t\t\t\tvar aid = \"\";\n");
      out.write("\t\t\t\t\tif(num>0){\n");
      out.write("\t\t\t\t\t\tstr+=$(\"#artlist\").html()+\"<table><tr>\";\n");
      out.write("\t\t\t\t\t\tfor(var i=0;i<num;i++) {\n");
      out.write("\t\t\t\t\t\t\tvar id = json.rows[i].id;\n");
      out.write("\t\t\t\t\t\t\tvar image = json.rows[i].image;\n");
      out.write("\t\t\t\t\t\t\tvar title = json.rows[i].title;\n");
      out.write("\t\t\t\t\t\t\tvar datetime = json.rows[i].createTime.substr(0,10);\n");
      out.write("\t\t\t\t\t\t\tvar url=\"");
      out.print(request.getContextPath());
      out.write("/jlb/detail.jsp?cid=\"+cid+\"&did=\"+id;\n");
      out.write("\t\t\t\t\t\t\t//aid 赋值\n");
      out.write("\t\t\t\t\t\t\tif (did == null||did==\"\"||did==\"null\") {\n");
      out.write("\t\t\t\t\t\t\t\t//aid = \"ccgdzs.new01.n1\";\n");
      out.write("\t\t\t\t\t\t\t\tdid = id;\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\tstr+=$(\"#artlist\").html()+\"<td><a href=\\\"\"+url+\"\\\"><img src=\"+image+\" width='140' height='110' style=\\\"padding:5px;border: 1px solid #CCCCCC\\\"><br><center style=\\\"margin-top:5px;\\\">\"+title+\"</center></a></td>\";\n");
      out.write("\t\t\t\t\t\t\tif((i+1)%5==0){\n");
      out.write("\t\t\t\t\t\t\t\tstr+=$(\"#artlist\").html()+\"</tr><tr>\";\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\tstr+=$(\"#artlist\").html()+\"</tr></table>\";\n");
      out.write("\t\t\t\t\t\t$(\"#artlist\").html(str);\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t}, \n");
      out.write("\t\t\t\t\"json\");\n");
      out.write("\t}else{\n");
      out.write("\t\t$.post(\"");
      out.print(request.getContextPath());
      out.write("/webdo/article/articleListByPage.do\", \n");
      out.write("\t\t\t\topt,\n");
      out.write("\t\t\t\tfunction(json){\n");
      out.write("\t\t\t\t\tvar str = \"\";\n");
      out.write("\t\t\t\t\t$(\"#artlist\").html(str);\n");
      out.write("\t\t\t\t\tvar num = json.rows.length;\n");
      out.write("\t\t\t\t\tvar aid = \"\";\n");
      out.write("\t\t\t\t\tif(num>0){\n");
      out.write("\t\t\t\t\t\tfor(var i=0;i<num;i++) {\n");
      out.write("\t\t\t\t\t\t\tvar id = json.rows[i].id;\n");
      out.write("\t\t\t\t\t\t\tvar image = json.rows[i].image;\n");
      out.write("\t\t\t\t\t\t\tvar title = json.rows[i].title;\n");
      out.write("\t\t\t\t\t\t\tvar datetime = json.rows[i].createTime.substr(0,10);\n");
      out.write("\t\t\t\t\t\t\tvar url=\"");
      out.print(request.getContextPath());
      out.write("/jlb/detail.jsp?cid=\"+cid+\"&did=\"+id;\n");
      out.write("\t\t\t\t\t\t\t//aid 赋值\n");
      out.write("\t\t\t\t\t\t\tif (did == null||did==\"\"||did==\"null\") {\n");
      out.write("\t\t\t\t\t\t\t\t//aid = \"ccgdzs.new01.n1\";\n");
      out.write("\t\t\t\t\t\t\t\tdid = id;\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\tstr=$(\"#artlist\").html()+\"<li><span>\"+datetime+\"</span><a href=\\\"\"+url+\"\\\">\"+title+\"</a></li>\";\n");
      out.write("\t\t\t\t\t\t\t$(\"#artlist\").html(str);\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\tvar totle = json.total;\n");
      out.write("\t\t\t\t\t//分页\n");
      out.write("\t\t\t\t\t$(\"#pagemenu\").pageMenuBar({\n");
      out.write("\t\t\t\t\t\trowPerPage:parseInt(opt.offset),\n");
      out.write("\t\t\t\t\t\tsumRow:parseInt(totle), \n");
      out.write("\t\t\t\t\t\tpageNo:parseInt(pageNo),\n");
      out.write("\t\t\t\t\t\tstate:1,\n");
      out.write("\t\t\t\t\t\tfunc:'getArticleListByPage',\n");
      out.write("\t\t\t\t\t\targs:'\"'+cid+'\"'\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\t\t\t\t}, \n");
      out.write("\t\t\t\t\"json\");\n");
      out.write("\t}\n");
      out.write("};\n");
      out.write("/* 成功案例 */\n");
      out.write("function getArticle_cgal(divid,size,opt){\n");
      out.write("\t$(\"#\"+divid+\"More\").attr(\"href\",\"");
      out.print(request.getContextPath());
      out.write("/jlb/list.jsp?cid=\"+opt.aid);\n");
      out.write("\t$.post(\"");
      out.print(request.getContextPath());
      out.write("/webdo/article/articleListByPage.do\", \n");
      out.write("\t\t\topt, \n");
      out.write("\t\t\tfunction(json){\n");
      out.write("\t\t\t\tvar str = \"\";\n");
      out.write("\t\t\t\t$(\"#\"+divid).html(str);\n");
      out.write("\t\t\t\tvar num = json.rows.length;\n");
      out.write("\t\t\t\tif(num>0){\n");
      out.write("\t\t\t\t\tfor(var i=0;i<num;i++) {\n");
      out.write("\t\t\t\t\t\tvar id = json.rows[i].id;\n");
      out.write("\t\t\t\t\t\tvar image = json.rows[i].image!=\"\"?json.rows[i].image:\"images/jctp_01.jpg\";\n");
      out.write("\t\t\t\t\t\tvar title = size!=null&&size!=\"\"&&json.rows[i].title.length>size?json.rows[i].title.substr(0,size)+\"...\":json.rows[i].title;\n");
      out.write("\t\t\t\t\t\tvar datetime = json.rows[i].createTime.substr(0,10);\n");
      out.write("\t\t\t\t\t\tvar url=\"");
      out.print(request.getContextPath());
      out.write("/jlb/detail.jsp?cid=\"+opt.aid+\"&did=\"+id;\n");
      out.write("\t\t\t\t\t\tstr=$(\"#\"+divid).html()+\"<li><a href=\\\"\"+url+\"\\\"><img width=\\\"140\\\" height=\\\"118\\\" alt=\\\"\"+json.rows[i].title+\"\\\" src=\\\"\"+image+\"\\\"/></a><br><span>\"+title+\"</span></li>\";\n");
      out.write("\t\t\t\t\t\t$(\"#\"+divid).html(str);\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t$(\".scrollleft\").imgscroll({\n");
      out.write("\t\t\t\t\tspeed: 20,    //图片滚动速度\n");
      out.write("\t\t\t\t\tamount: 0,    //图片滚动过渡时间\n");
      out.write("\t\t\t\t\twidth: 1,     //图片滚动步数\n");
      out.write("\t\t\t\t\tdir: \"left\"   // \"left\" 或 \"up\" 向左或向上滚动\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t\t}, \n");
      out.write("\t\t\t\"json\");\n");
      out.write("};\n");
      out.write("\n");
      out.write("getArticle_cgal(\"case\",21,{aid:\"jlb.case\",start:'0',offset:'100'}, 3);\n");
      out.write("</script>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("/* scrollleft */\n");
      out.write(".scrollleft{width:920px;padding:5px 20px 0px 20px;margin:0px auto;}\n");
      out.write(".scrollleft li{float:left;margin-right:7px;display:inline;width:158px;text-align:center;line-height:19px}\n");
      out.write(".scrollleft img{width:136px;height:100px;padding:10px;border:solid 1px #ddd;}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<div class=\"body\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("function getArticleList(divid,size,opt,type){\n");
      out.write("\t$(\"#\"+divid+\"More\").attr(\"href\",\"");
      out.print(request.getContextPath());
      out.write("/jlb/list.jsp?cid=\"+opt.aid);\n");
      out.write("\t//获得文章列表\n");
      out.write("\n");
      out.write("\t$.post(\"");
      out.print(request.getContextPath());
      out.write("/webdo/article/articleListByPage.do\", \n");
      out.write("\t\t\topt, \n");
      out.write("\t\t\t\n");
      out.write("\t\t\tfunction(json){\n");
      out.write("\t\t\t\tvar str = \"\";\n");
      out.write("\t\t\t\t$(\"#\"+divid).html(str);\n");
      out.write("\t\t\t\tvar num = json.rows.length;\n");
      out.write("\t\t\t\tvar aid = \"\";\n");
      out.write("\t\t\t\tif(num>0){\n");
      out.write("\t\t\t\t\tfor(var i=0;i<num;i++) { \n");
      out.write("\t\t\t\t\t\tvar id = json.rows[i].id;\n");
      out.write("\t\t\t\t\t\tvar image = json.rows[i].image;\n");
      out.write("\t\t\t\t\t\tvar title = size!=null&&size!=\"\"&&json.rows[i].title.length>size?json.rows[i].title.substr(0,size)+\"...\":json.rows[i].title;\n");
      out.write("\t\t\t\t\t\tvar text = size!=null&&size!=\"\"&&json.rows[i].text.length>size?json.rows[i].text.substr(0,size)+\"...\":json.rows[i].text;\n");
      out.write("\t\t\t\t\t\tvar datetime = json.rows[i].createTime.substr(0,10);\n");
      out.write("\t\t\t\t\t\tvar url=\"");
      out.print(request.getContextPath());
      out.write("/jlb/detail.jsp?cid=\"+opt.aid+\"&did=\"+id;\n");
      out.write("\t\t\t\t\t\tif(type == 1){\n");
      out.write("\t\t\t\t\t\t\tstr=$(\"#\"+divid).html()+\"<li><a href=\\\"\"+url+\"\\\">\"+text+\"</li>\";\n");
      out.write("\t\t\t\t\t\t}else if(type == 2){\n");
      out.write("\t\t\t\t\t\t\tstr=$(\"#\"+divid).html()+\"<li><a href=\\\"\"+url+\"\\\">\"+title+\"</a></li>\"; \n");
      out.write("\t\t\t\t\t\t} else{\n");
      out.write("\t\t\t\t\t\t\tstr=$(\"#\"+divid).html()+\"<a href=\\\"\"+url+\"\\\">\"+text+\"\"; \n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t$(\"#\"+divid).html(str);\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}, \n");
      out.write("\t\t\t\"json\");\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<div class=\"top\">\n");
      out.write("<div class=\"logo\"></div>\n");
      out.write("<form action=\"");
      out.print(request.getContextPath());
      out.write("/jlb/list.jsp\" method=\"post\">\n");
      out.write("<div class=\"search\">搜索\n");
      out.write("  <input type=\"text\" class=\"input\" name=\"cid\" />\n");
      out.write("  <input type=\"hidden\" value=\"search\" name=\"type\" />\n");
      out.write("  <input name=\"\" type=\"submit\" class=\"button\" id=\"GO\" value=\"GO\"  />\n");
      out.write("</div>\n");
      out.write(" </form>\n");
      out.write("</div>\n");
      out.write("<div class=\"nav2\">\n");
      out.write("<ul>\n");
      out.write("<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\" id=\"aa\">首页</a></li>\n");
      out.write("<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/jlb/detail.jsp?cid=jlb.profile&did=588\" id=\"b\">公司概况</a></li>\n");
      out.write("<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/jlb/list.jsp?cid=jlb.information\" id=\"c\">最新资讯</a></li>\n");
      out.write("<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/jlb/list.jsp?cid=jlb.service\" id=\"d\">服务项目</a></li>\n");
      out.write("<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/jlb/list.jsp?cid=jlb.case&type=cgal\" id=\"e\">成功案例</a></li>\n");
      out.write("<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/jlb/list.jsp?cid=jlb.support\" id=\"f\">技术支持</a></li>\n");
      out.write("<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/jlb/list.jsp?cid=jlb.download\" id=\"g\">软件下载</a></li>\n");
      out.write("<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/jlb/message.jsp\" id=\"h\">在线留言</a></li>\n");
      out.write("<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/jlb/detail.jsp?cid=jlb.contact&did=589\" id=\"i\">联系我们</a></li>\n");
      out.write("</ul>\n");
      out.write("</div>\n");
      out.write("    \n");
      out.write("\n");
      out.write("\n");
      out.write("<p id=\"back-to-top\"><a href=\"#top\"><span style=\"background: url('./images/top.png');\"></span></a></p>\n");
      out.write("<div class=\"con20\">\n");
      out.write("\n");
      out.write("<div class=\"con21\">\n");
      out.write("<ul>\n");
      out.write("<li><h2><a href=\"");
      out.print(request.getContextPath());
      out.write("/jlb/list.jsp?cid=jlb.service\" id=\"link_text\">服务项目</a></h2>\n");
      out.write("<h3>Services</h3></li>\n");
      out.write("<li><h2><a href=\"");
      out.print(request.getContextPath());
      out.write("/jlb/list.jsp?cid=jlb.support\">技术支持</a></h2>\n");
      out.write("<h3>Technical Support</h3></li>\n");
      out.write("<li><h2><a href=\"");
      out.print(request.getContextPath());
      out.write("/jlb/list.jsp?cid=jlb.download\">软件下载</a></h2>\n");
      out.write("<h3>Software Downloads</h3></li>\n");
      out.write("<li><h2><a href=\"");
      out.print(request.getContextPath());
      out.write("/jlb/detail.jsp?cid=jlb.contact&did=589\">联系方式</a></h2>\n");
      out.write("<h3>Contact</h3></li>\n");
      out.write("</ul>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write(" \t\t<div class=\"con22\">\n");
      out.write(" \t\t\t<div class=\"con22_top\"></div>\n");
      out.write("           \t  <div class=\"con22_main\">\n");
      out.write("           \t  <ul id=\"artlist\"> </ul>\n");
      out.write("           \t  <p><span id=\"pagemenu\"></span></p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"con22_bottom\"></div>\n");
      out.write("        </div><!--右侧-->\n");
      out.write("</div>\n");
      out.write("\r\n");
      out.write(" <div class=\"con13\">\r\n");
      out.write("<div id=\"demo\">\r\n");
      out.write("\t<div id=\"indemo\">\r\n");
      out.write("\t<div id=\"demo1\" class=\"scrollleft\">\r\n");
      out.write("\t\t<ul id=\"case\">\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write(" <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/js/cgal.js\"></script>\t\t\t\r\n");
      out.write("</div>");
      out.write("\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("<div id=\"footer\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    long count = CountPerson.replaceCount(request.getRealPath("/")+"count.txt");
   if(session.getAttribute("CHEN_CHAO")==null){
    session.setAttribute("CHEN_CHAO","123");
    session.setMaxInactiveInterval(60*60*24);
   count = count+1;
   CountPerson.saveCount(request.getRealPath("/")+"count.txt",count);
}
 
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t\t\t$(function() {\n");
      out.write("\t\t\t\t//按获得文章\n");
      out.write("\t\t\t\t$.post(\"");
      out.print(request.getContextPath());
      out.write("/webdo/article/onearticle.do\", \n");
      out.write("\t\t\t\t\t\t{aid:\"jlbhtml.foot\",id:\"\"}, \n");
      out.write("\t\t\t\t\t\tfunction(json){\n");
      out.write("\t\t\t\t\t\t\tvar id = json.id;\n");
      out.write("\t\t\t\t\t\t\tvar titlez = json.title;\n");
      out.write("\t\t\t\t\t\t\tvar text = json.text;\n");
      out.write("\t\t\t\t\t\t\tif(text==null||text.Trim()==\"\")\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#bq\").html(\"\");\n");
      out.write("\t\t\t\t\t\t\telse\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#bq\").html(text);\n");
      out.write("\t\t\t\t\t\t}, \n");
      out.write("\t\t\t\t\t\t\"json\");\n");
      out.write("\t\t\t});\n");
      out.write("\n");
      out.write("\t\t\tfunction toIndex(){\n");
      out.write("\t\t\t//返回首页\n");
      out.write("\t\t\t\tlocation=\"./index.jsp\";\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tfunction toNew(){\n");
      out.write("\t\t\t//跳转到新闻页\n");
      out.write("\t\t\t\tlocation=\"./newlist.jsp?cid=ccgdzs.newlist\";\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t/* 获取页底数据 */\n");
      out.write("\tgetArticleList(\"bottom\",1000,{aid:\"jlb.foot\",start:'0',offset:'6'}, 3);\n");
      out.write("\tgetArticleList(\"link\",1000,{aid:\"jlb.link\",start:'0',offset:'6'}, 3);\n");
      out.write("</script>\n");
      out.write("<div class=\"links\" id=\"link\">\n");
      out.write("\t\n");
      out.write("</div>\n");
      out.write("<div class=\"footer\">\n");
      out.write("<ul>\n");
      out.write("<li><img src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/images/bottom_01.png\" /></li>\n");
      out.write("<li><img src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/images/bottom_02.png\" /></li>\n");
      out.write("<li><img src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/images/bottom_03.png\" /></li>\n");
      out.write("<li><img src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/images/bottom_04.png\" /></li>\n");
      out.write("<li><img src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/images/bottom_05.png\" /></li>\n");
      out.write("<li><img src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/images/bottom_06.png\" /></li>\n");
      out.write("</ul>\n");
      out.write("</div>\n");
      out.write("<div class=\"footer_text\" id=\"bottom\">\n");
      out.write("</div>\n");
      out.write(" \n");
      out.write("  ");
      out.write("\n");
      out.write("</div>\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<div id=\"KeFuDiv\" class=\"KeFuDiv\">\r\n");
      out.write("  <div><img src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/images/up_001.gif\" width=\"105\" border=\"0\" usemap=\"#Map\" style=\"cursor:move;\" title=\"拖动\" onmousedown=\"MoveDiv(KeFuDiv,event);\"></div>\r\n");
      out.write("    <div class=\"KeFuTitle\"><a href=\"#\" onclick=\"javascript:window.open('http://wpa.qq.com/msgrd?V=1&Uin=1305457111');\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/images/list_001.gif\" /></a></div>\r\n");
      out.write("    <div class=\"KeFuTitle\"><a href=\"#\" onclick=\"javascript:window.open('http://wpa.qq.com/msgrd?V=1&Uin=1305457111');\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/images/list_003.gif\" /></a></div>  \r\n");
      out.write("     <div class=\"KeFuTitle\"><a href=\"#\" onclick=\"javascript:window.open('http://wpa.qq.com/msgrd?V=1&Uin=1305457111');\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/images/list_002.gif\" /></a></div>\r\n");
      out.write("<div class=\"div_img\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/images/bot_001.gif\" border=\"0\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("//初始位置\r\n");
      out.write("gID(\"KeFuDiv\").style.top = (document.documentElement.clientHeight - gID(\"KeFuDiv\").offsetHeight)/2 +\"px\";\r\n");
      out.write("gID(\"KeFuDiv\").style.right = document.documentElement.clientWidth - gID(\"KeFuDiv\").offsetWidth +\"px\";\r\n");
      out.write("//开始滚动\r\n");
      out.write("ScrollDiv('KeFuDiv');\r\n");
      out.write("</script>");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
