package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.saturn.website.WebUtils;
import com.saturn.website.Content;
import java.util.List;
import com.saturn.website.Article;
import com.saturn.website.WebUtils;
import com.saturn.website.Content;
import com.saturn.website.CountPerson;
import java.util.List;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(4);
    _jspx_dependants.add("/include/include.jsp");
    _jspx_dependants.add("/jlb/include/top.jsp");
    _jspx_dependants.add("/jlb/include/foot.jsp");
    _jspx_dependants.add("/jlb/include/cs.jsp");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=EmulateIE7\" />\n");
      out.write("<title>金兰宝科技有限公司</title>\n");
      out.write("\n");
      out.write("\n");
      out.write("<link rel=\"shortcut icon\" href=\"../favicon.ico\" type=\"image/x-icon\" />\n");
      out.write("<meta name=\"description\" content=\"金兰宝\" />\n");
      out.write("<meta name =\"keywords\" content=\"金兰宝\">\n");
      out.write("\n");
      out.write(" <script src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/js/jquery-1.9.1.min.js\" type=\"text/javascript\"></script>\n");
      out.write(" <script src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/js/jquery.litenav.js\" type=\"text/javascript\"></script>\n");
      out.write(" <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/js/lrtk.js\"></script>\n");
      out.write(" <link href=\"");
      out.print(request.getContextPath());
      out.write("/jlb/css/index.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write(" \n");
      out.write(" <link href=\"");
      out.print(request.getContextPath());
      out.write("/jlb/css/style.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write(" <link href=\"");
      out.print(request.getContextPath());
      out.write("/jlb/css/top.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write(" <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/js/pageMenuBar.js\"></script>\n");
      out.write(" <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/js/imgscroll.js\"></script>\n");
      out.write(" <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/js/back-to-top.js\"></script>\n");
      out.write(" <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/js/Marquee.js\"></script> \n");
      out.write("\n");
      out.write("  <style type=\"text/css\">\n");
      out.write("#scrollDiv{min-height:25px;line-height:35px;}\n");
      out.write("#scrollDiv li{height:25px;padding-left:10px;}\n");
      out.write("\n");
      out.write("*{margin:0;padding:0;list-style-type:none;}\n");
      out.write("a,img{border:0;}\n");
      out.write("/* scrollleft */\n");
      out.write(".scrollleft{width:920px;padding:5px 20px 0px 20px;margin:0px auto;}\n");
      out.write(".scrollleft li{float:left;margin-right:7px;display:inline;width:158px;text-align:center;line-height:19px}\n");
      out.write(".scrollleft img{width:136px;height:100px;padding:10px;border:solid 1px #ddd;}\n");
      out.write("\n");
      out.write("a{color:#333;}\n");
      out.write("a:hover{color:#3366cc;text-decoration:none;}\n");
      out.write("/* marquee6 */\n");
      out.write("#marquee6{width:360px;height:135px; overflow:hidden;}\n");
      out.write("#marquee6 ul li{padding:0 10px;line-height:20px;height:20px;overflow:hidden;}\n");
      out.write("/* control */\n");
      out.write(".timescroll{float:right;}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write(" <script type=\"text/javascript\">\n");
      out.write(" $(function() {\n");
      out.write("\t\t//获得文章列表\n");
      out.write("\t\tgetArticleList(\"profile\",450,{aid:\"jlb.profile\",start:'0',offset:'1'}, 1);\n");
      out.write("\t\tgetArticle_zxzx(\"news\",14,{aid:\"jlb.information \",start:'0',offset:'6'}, 2);\n");
      out.write("\t\tgetArticleList(\"service\",18,{aid:\"jlb.service\",start:'0',offset:'6'}, 2);\n");
      out.write("\t\tgetArticleList(\"support\",18,{aid:\"jlb.support\",start:'0',offset:'6'}, 2);\n");
      out.write("\t\tgetArticleList(\"download\",21,{aid:\"jlb.download\",start:'0',offset:'6'}, 2);\n");
      out.write("\t\tgetArticle_cgal(\"case\",21,{aid:\"jlb.case\",start:'0',offset:'16'}, 3);\n");
      out.write("\t\t});\n");
      out.write(" \n");
      out.write(" /* 成功案例 插件*/\n");
      out.write(" function getArticle_cgal(divid,size,opt){\n");
      out.write("\t\t$(\"#\"+divid+\"More\").attr(\"href\",\"");
      out.print(request.getContextPath());
      out.write("/jlb/list.jsp?cid=\"+opt.aid);\n");
      out.write("\t\t$.post(\"");
      out.print(request.getContextPath());
      out.write("/webdo/article/articleListByPage.do\", \n");
      out.write("\t\t\t\topt, \n");
      out.write("\t\t\t\tfunction(json){\n");
      out.write("\t\t\t\t\tvar str = \"\";\n");
      out.write("\t\t\t\t\t$(\"#\"+divid).html(str);\n");
      out.write("\t\t\t\t\tvar num = json.rows.length;\n");
      out.write("\t\t\t\t\tif(num>0){\n");
      out.write("\t\t\t\t\t\tfor(var i=0;i<num;i++) {\n");
      out.write("\t\t\t\t\t\t\tvar id = json.rows[i].id;\n");
      out.write("\t\t\t\t\t\t\tvar image = json.rows[i].image!=\"\"?json.rows[i].image:\"images/jctp_01.jpg\";\n");
      out.write("\t\t\t\t\t\t\tvar title = size!=null&&size!=\"\"&&json.rows[i].title.length>size?json.rows[i].title.substr(0,size)+\"...\":json.rows[i].title;\n");
      out.write("\t\t\t\t\t\t\tvar datetime = json.rows[i].createTime.substr(0,10);\n");
      out.write("\t\t\t\t\t\t\tvar url=\"");
      out.print(request.getContextPath());
      out.write("/jlb/detail.jsp?cid=\"+opt.aid+\"&did=\"+id;\n");
      out.write("\t\t\t\t\t\t\tstr=$(\"#\"+divid).html()+\"<li><a href=\\\"\"+url+\"\\\"><img width=\\\"160\\\" height=\\\"118\\\" alt=\\\"\"+json.rows[i].title+\"\\\" src=\\\"\"+image+\"\\\"/></a><span>\"+title+\"</span></li>\";\n");
      out.write("\t\t\t\t\t\t\t$(\"#\"+divid).html(str);\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t$(\".scrollleft\").imgscroll({\n");
      out.write("\t\t\t\t\t\tspeed: 20,    //图片滚动速度\n");
      out.write("\t\t\t\t\t\tamount: 0,    //图片滚动过渡时间\n");
      out.write("\t\t\t\t\t\twidth: 1,     //图片滚动步数\n");
      out.write("\t\t\t\t\t\tdir: \"left\"   // \"left\" 或 \"up\" 向左或向上滚动\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\t\t\t\t}, \n");
      out.write("\t\t\t\t\"json\");\n");
      out.write("\t};\n");
      out.write(" /* 最新资讯插件*/\n");
      out.write(" function getArticle_zxzx(divid,size,opt){\n");
      out.write("\t\t$(\"#\"+divid+\"More\").attr(\"href\",\"");
      out.print(request.getContextPath());
      out.write("/jlb/list.jsp?cid=\"+opt.aid);\n");
      out.write("\t\t$.post(\"");
      out.print(request.getContextPath());
      out.write("/webdo/article/articleListByPage.do\", \n");
      out.write("\t\t\t\topt, \n");
      out.write("\t\t\t\tfunction(json){\n");
      out.write("\t\t\t\t\tvar str = \"\";\n");
      out.write("\t\t\t\t\t$(\"#\"+divid).html(str);\n");
      out.write("\t\t\t\t\tvar num = json.rows.length;\n");
      out.write("\t\t\t\t\tif(num>0){\n");
      out.write("\t\t\t\t\t\tfor(var i=0;i<num;i++) {\n");
      out.write("\t\t\t\t\t\t\tvar id = json.rows[i].id;\n");
      out.write("\t\t\t\t\t\t\tvar image = json.rows[i].image!=\"\"?json.rows[i].image:\"images/jctp_01.jpg\";\n");
      out.write("\t\t\t\t\t\t\tvar title = size!=null&&size!=\"\"&&json.rows[i].title.length>size?json.rows[i].title.substr(0,size)+\"...\":json.rows[i].title;\n");
      out.write("\t\t\t\t\t\t\tvar datetime = json.rows[i].createTime.substr(0,10);\n");
      out.write("\t\t\t\t\t\t\tvar url=\"");
      out.print(request.getContextPath());
      out.write("/jlb/detail.jsp?cid=\"+opt.aid+\"&did=\"+id;\n");
      out.write("\t\t\t\t\t\t\tstr=$(\"#\"+divid).html()+\"<li><span class=\\\"timescroll\\\">\"+datetime+\"</span><a href=\\\"\"+url+\"\\\">\"+title+\"</a></li>\";\n");
      out.write("\t\t\t\t\t\t\t$(\"#\"+divid).html(str);\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t$('#marquee6').kxbdSuperMarquee({\n");
      out.write("\t\t\t\t\t\tisMarquee:true,\n");
      out.write("\t\t\t\t\t\tisEqual:false,\n");
      out.write("\t\t\t\t\t\tscrollDelay:30,\n");
      out.write("\t\t\t\t\t\tcontrolBtn:{up:'#goUM',down:'#goDM'},\n");
      out.write("\t\t\t\t\t\tdirection:'up'\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\t\t\t\t}, \n");
      out.write("\t\t\t\t\"json\");\n");
      out.write("\t};\n");
      out.write("\t\n");
      out.write(" </script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<div class=\"body\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("function getArticleList(divid,size,opt,type){\n");
      out.write("\t$(\"#\"+divid+\"More\").attr(\"href\",\"");
      out.print(request.getContextPath());
      out.write("/jlb/list.jsp?cid=\"+opt.aid);\n");
      out.write("\t//获得文章列表\n");
      out.write("\n");
      out.write("\t$.post(\"");
      out.print(request.getContextPath());
      out.write("/webdo/article/articleListByPage.do\", \n");
      out.write("\t\t\topt, \n");
      out.write("\t\t\t\n");
      out.write("\t\t\tfunction(json){\n");
      out.write("\t\t\t\tvar str = \"\";\n");
      out.write("\t\t\t\t$(\"#\"+divid).html(str);\n");
      out.write("\t\t\t\tvar num = json.rows.length;\n");
      out.write("\t\t\t\tvar aid = \"\";\n");
      out.write("\t\t\t\tif(num>0){\n");
      out.write("\t\t\t\t\tfor(var i=0;i<num;i++) { \n");
      out.write("\t\t\t\t\t\tvar id = json.rows[i].id;\n");
      out.write("\t\t\t\t\t\tvar image = json.rows[i].image;\n");
      out.write("\t\t\t\t\t\tvar title = size!=null&&size!=\"\"&&json.rows[i].title.length>size?json.rows[i].title.substr(0,size)+\"...\":json.rows[i].title;\n");
      out.write("\t\t\t\t\t\tvar text = size!=null&&size!=\"\"&&json.rows[i].text.length>size?json.rows[i].text.substr(0,size)+\"...\":json.rows[i].text;\n");
      out.write("\t\t\t\t\t\tvar datetime = json.rows[i].createTime.substr(0,10);\n");
      out.write("\t\t\t\t\t\tvar url=\"");
      out.print(request.getContextPath());
      out.write("/jlb/detail.jsp?cid=\"+opt.aid+\"&did=\"+id;\n");
      out.write("\t\t\t\t\t\tif(type == 1){\n");
      out.write("\t\t\t\t\t\t\tstr=$(\"#\"+divid).html()+\"<li><a href=\\\"\"+url+\"\\\">\"+text+\"</li>\";\n");
      out.write("\t\t\t\t\t\t}else if(type == 2){\n");
      out.write("\t\t\t\t\t\t\tstr=$(\"#\"+divid).html()+\"<li><a href=\\\"\"+url+\"\\\">\"+title+\"</a></li>\"; \n");
      out.write("\t\t\t\t\t\t} else{\n");
      out.write("\t\t\t\t\t\t\tstr=$(\"#\"+divid).html()+\"<a href=\\\"\"+url+\"\\\">\"+text+\"\"; \n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t$(\"#\"+divid).html(str);\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}, \n");
      out.write("\t\t\t\"json\");\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<div class=\"top\">\n");
      out.write("<div class=\"logo\"></div>\n");
      out.write("<form action=\"");
      out.print(request.getContextPath());
      out.write("/jlb/list.jsp\" method=\"post\">\n");
      out.write("<div class=\"search\">搜索\n");
      out.write("  <input type=\"text\" class=\"input\" name=\"cid\" />\n");
      out.write("  <input type=\"hidden\" value=\"search\" name=\"type\" />\n");
      out.write("  <input name=\"\" type=\"submit\" class=\"button\" id=\"GO\" value=\"GO\"  />\n");
      out.write("</div>\n");
      out.write(" </form>\n");
      out.write("</div>\n");
      out.write("<div class=\"nav2\">\n");
      out.write("<ul>\n");
      out.write("<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\" id=\"aa\">首页</a></li>\n");
      out.write("<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/jlb/detail.jsp?cid=jlb.profile&did=588\" id=\"b\">公司概况</a></li>\n");
      out.write("<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/jlb/list.jsp?cid=jlb.information\" id=\"c\">最新资讯</a></li>\n");
      out.write("<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/jlb/list.jsp?cid=jlb.service\" id=\"d\">服务项目</a></li>\n");
      out.write("<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/jlb/list.jsp?cid=jlb.case&type=cgal\" id=\"e\">成功案例</a></li>\n");
      out.write("<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/jlb/list.jsp?cid=jlb.support\" id=\"f\">技术支持</a></li>\n");
      out.write("<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/jlb/list.jsp?cid=jlb.download\" id=\"g\">软件下载</a></li>\n");
      out.write("<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/jlb/message.jsp\" id=\"h\">在线留言</a></li>\n");
      out.write("<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/jlb/detail.jsp?cid=jlb.contact&did=589\" id=\"i\">联系我们</a></li>\n");
      out.write("</ul>\n");
      out.write("</div>\n");
      out.write("    \n");
      out.write("\n");
      out.write("\n");
      out.write("<p id=\"back-to-top\"><a href=\"#top\"><span style=\"background: url('jlb/images/top.png');\"></span></a></p>\n");
      out.write("<div class=\"con1\">\n");
      out.write("<div class=\"con2\">\n");
      out.write("<div id=\"hotpic\">\n");
      out.write("        <div id=\"NewsPic\">\n");
      out.write("            <a target=\"_blank\" href=\"#\" style=\"visibility: visible; display: block;\">\n");
      out.write("                <img width=\"793\" height=\"307\" src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/images/1.jpg\" class=\"Picture\" alt=\"测试用图片\" title=\"第1张图片的说明文字\" /></a>\n");
      out.write("            <a style=\"visibility: hidden; display: none;\" target=\"_blank\" href=\"#\">\n");
      out.write("                <img class=\"Picture\" src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/images/2.jpg\" style=\"width: 793px; height: 307px;\" alt=\"测试用图片\" title=\"第2张图片的说明文字\" /></a>\n");
      out.write("            <a style=\"visibility: hidden; display: none;\" target=\"_blank\" href=\"#\">\n");
      out.write("                <img class=\"Picture\" src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/images/3.jpg\" style=\"width: 793px; height: 307px;\" alt=\"测试用图片\" title=\"第3张图片的说明文字\" /></a>\n");
      out.write("            <a style=\"visibility: hidden; display: none;\" target=\"_blank\" href=\"#\">\n");
      out.write("                <img class=\"Picture\" src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/images/4.jpg\" style=\"width: 793px; height: 307px;\" alt=\"测试用图片\" title=\"第4张图片的说明文字\" /></a>\n");
      out.write("            <a style=\"visibility: hidden; display: none;\" target=\"_blank\" href=\"#\">\n");
      out.write("                <img width=\"793px\" height=\"307px\" src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/images/5.jpg\" class=\"Picture\" alt=\"测试用图片\" title=\"第5张图片的说明文字\" /></a>\n");
      out.write("            <div class=\"Nav\">\n");
      out.write("                <span class=\"Normal\">5</span>\n");
      out.write("                <span class=\"Normal\">4</span>\n");
      out.write("                <span class=\"Normal\">3</span>\n");
      out.write("                <span class=\"Normal\">2</span>\n");
      out.write("                <span class=\"Cur\">1</span>            </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("        $('#hotpic').liteNav(2000);\n");
      out.write("    </script>\n");
      out.write("</div>\n");
      out.write("<div class=\"con3\">\n");
      out.write("<h2>电脑医生到您家</h2>\n");
      out.write("<ul>\n");
      out.write("<li><h3><a href=\"#\"></a>各大品牌笔记本<p>维修成功率高</p><p>清理技术好</p></h3><a href=\"#\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/images/pic_03.jpg\" /></a></li>\n");
      out.write("<li><h3><a href=\"#\"></a>台式电脑维修<p>上门安装系统</p><p>疑难杂症维修</p></h3><a href=\"#\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/images/pic_04.jpg\" /></a></li>\n");
      out.write("<li><h3><a href=\"#\"></a>显示器维修<p>液晶显示屏</p><p>LED屏幕维修</p></h3><a href=\"#\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/images/pic_05.jpg\" /></a></li>\n");
      out.write("</ul>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("<div class=\"con4\">\n");
      out.write("<!-- 公司简介 -->\n");
      out.write("<div class=\"con5\" id=\"profile\"></div>\n");
      out.write("\n");
      out.write("<div class=\"con6\">\n");
      out.write("<p>15948321834</p>\n");
      out.write("<p>0431-81756788</p>\n");
      out.write("<p>1084809237</p>\n");
      out.write("<p>1084809237@qq.com</p>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("<div class=\"con7\">\n");
      out.write("\t<!-- 最新资讯 -->\n");
      out.write("\t<div class=\"con8\" id=\"scrollDiv\">\n");
      out.write("\t<p class=\"xmore\"><a href=\"#\" id=\"newsMore\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/images/more_01.png\" border=\"0\" /></a></p>\n");
      out.write("\t<!-- <ul id=\"news\"></ul> -->\n");
      out.write("\t<div id=\"marquee6\">\n");
      out.write("\t\t<ul id=\"news\">\n");
      out.write("\t\t</ul>\n");
      out.write("\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- 服务项目 -->\n");
      out.write("\t<div class=\"con9\">\n");
      out.write("\t<p class=\"xmore\"><a href=\"#\" id=\"serviceMore\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/images/more_02.png\" border=\"0\" /></a></p>\n");
      out.write("\t\t<ul id=\"service\"></ul>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<div class=\"con10\">\n");
      out.write("\t<!-- 技术支持 -->\n");
      out.write("\t<div class=\"con11\">\n");
      out.write("\t<p class=\"xmore\"><a href=\"#\" id=\"supportMore\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/images/more_03.png\" border=\"0\" /></a></p>\n");
      out.write("\t<ul id=\"support\"></ul>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- 软件下载 -->\n");
      out.write("\t<div class=\"con12\">\n");
      out.write("\t<p class=\"xmore\"><a href=\"#\" id=\"downloadMore\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/images/more_04.png\" border=\"0\" /></a></p>\n");
      out.write("\t<ul id=\"download\"></ul>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<div class=\"con13\">\n");
      out.write("<!-- 成功案例 -->\n");
      out.write("<div id=\"demo\">\n");
      out.write("\t<div class=\"scrollleft\">\n");
      out.write("\t\t<ul id=\"case\">\n");
      out.write("\t\t</ul>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("<div id=\"footer\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    long count = CountPerson.replaceCount(request.getRealPath("/")+"count.txt");
   if(session.getAttribute("CHEN_CHAO")==null){
    session.setAttribute("CHEN_CHAO","123");
    session.setMaxInactiveInterval(60*60*24);
   count = count+1;
   CountPerson.saveCount(request.getRealPath("/")+"count.txt",count);
}
 
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t\t\t$(function() {\n");
      out.write("\t\t\t\t//按获得文章\n");
      out.write("\t\t\t\t$.post(\"");
      out.print(request.getContextPath());
      out.write("/webdo/article/onearticle.do\", \n");
      out.write("\t\t\t\t\t\t{aid:\"jlbhtml.foot\",id:\"\"}, \n");
      out.write("\t\t\t\t\t\tfunction(json){\n");
      out.write("\t\t\t\t\t\t\tvar id = json.id;\n");
      out.write("\t\t\t\t\t\t\tvar titlez = json.title;\n");
      out.write("\t\t\t\t\t\t\tvar text = json.text;\n");
      out.write("\t\t\t\t\t\t\tif(text==null||text.Trim()==\"\")\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#bq\").html(\"\");\n");
      out.write("\t\t\t\t\t\t\telse\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#bq\").html(text);\n");
      out.write("\t\t\t\t\t\t}, \n");
      out.write("\t\t\t\t\t\t\"json\");\n");
      out.write("\t\t\t});\n");
      out.write("\n");
      out.write("\t\t\tfunction toIndex(){\n");
      out.write("\t\t\t//返回首页\n");
      out.write("\t\t\t\tlocation=\"./index.jsp\";\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tfunction toNew(){\n");
      out.write("\t\t\t//跳转到新闻页\n");
      out.write("\t\t\t\tlocation=\"./newlist.jsp?cid=ccgdzs.newlist\";\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t/* 获取页底数据 */\n");
      out.write("\tgetArticleList(\"bottom\",1000,{aid:\"jlb.foot\",start:'0',offset:'6'}, 3);\n");
      out.write("\tgetArticleList(\"link\",1000,{aid:\"jlb.link\",start:'0',offset:'6'}, 3);\n");
      out.write("</script>\n");
      out.write("<div class=\"links\" id=\"link\">\n");
      out.write("\t\n");
      out.write("</div>\n");
      out.write("<div class=\"footer\">\n");
      out.write("<ul>\n");
      out.write("<li><img src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/images/bottom_01.png\" /></li>\n");
      out.write("<li><img src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/images/bottom_02.png\" /></li>\n");
      out.write("<li><img src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/images/bottom_03.png\" /></li>\n");
      out.write("<li><img src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/images/bottom_04.png\" /></li>\n");
      out.write("<li><img src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/images/bottom_05.png\" /></li>\n");
      out.write("<li><img src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/images/bottom_06.png\" /></li>\n");
      out.write("</ul>\n");
      out.write("</div>\n");
      out.write("<div class=\"footer_text\" id=\"bottom\">\n");
      out.write("</div>\n");
      out.write(" \n");
      out.write("  ");
      out.write("\n");
      out.write("</div>\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<div id=\"KeFuDiv\" class=\"KeFuDiv\">\r\n");
      out.write("  <div><img src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/images/up_001.gif\" width=\"105\" border=\"0\" usemap=\"#Map\" style=\"cursor:move;\" title=\"拖动\" onmousedown=\"MoveDiv(KeFuDiv,event);\"></div>\r\n");
      out.write("    <div class=\"KeFuTitle\"><a href=\"#\" onclick=\"javascript:window.open('http://wpa.qq.com/msgrd?V=1&Uin=1305457111');\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/images/list_001.gif\" /></a></div>\r\n");
      out.write("    <div class=\"KeFuTitle\"><a href=\"#\" onclick=\"javascript:window.open('http://wpa.qq.com/msgrd?V=1&Uin=1305457111');\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/images/list_003.gif\" /></a></div>  \r\n");
      out.write("     <div class=\"KeFuTitle\"><a href=\"#\" onclick=\"javascript:window.open('http://wpa.qq.com/msgrd?V=1&Uin=1305457111');\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/images/list_002.gif\" /></a></div>\r\n");
      out.write("<div class=\"div_img\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/jlb/images/bot_001.gif\" border=\"0\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("//初始位置\r\n");
      out.write("gID(\"KeFuDiv\").style.top = (document.documentElement.clientHeight - gID(\"KeFuDiv\").offsetHeight)/2 +\"px\";\r\n");
      out.write("gID(\"KeFuDiv\").style.right = document.documentElement.clientWidth - gID(\"KeFuDiv\").offsetWidth +\"px\";\r\n");
      out.write("//开始滚动\r\n");
      out.write("ScrollDiv('KeFuDiv');\r\n");
      out.write("</script>");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
